language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version
  # build containers
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  # tag containers
  - docker tag udagram-api-feed hoangtrungnghia/udagram-api-feed-v2:v1
  - docker tag udagram-api-user hoangtrungnghia/udagram-api-user-v2:v1
  - docker tag udagram-frontend hoangtrungnghia/udagram-frontend-v2:v1
  - docker tag udagram-reverseproxy hoangtrungnghia/udagram-reverseproxy-v2:v1

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push hoangtrungnghia/udagram-api-user-v2:v1
  - docker push hoangtrungnghia/udagram-api-feed-v2:v1
  - docker push hoangtrungnghia/udagram-frontend-v2:v1
  - docker push hoangtrungnghia/udagram-reverseproxy-v2:v1
  
  - docker pull hoangtrungnghia/udagram-api-user-v2:v1
  - docker pull hoangtrungnghia/udagram-api-feed-v2:v1
  - docker pull hoangtrungnghia/udagram-frontend-v2:v1
  - docker pull hoangtrungnghia/udagram-reverseproxy-v2:v1