apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: FwoGZXIvYXdzEN///////////wEaDN9P8VAOPA7Bq//yDSLVAb0LpSQkpmTzXmHCa/HUGDpx0e2VoEnKfsaDHLhNJhAtMrn8EdreyqIJ9PRJqF0KQ2WeoGSgSvB+D8+fj4j8hM8fHAxW1BTHIafFXNi22hVzHoN+em4Z1VN5F9JVhXhXlxDLNVL6wsWp5/+qCfTdqW7cc/C6A+lTXWNYSJkfdtSH/TqKdyIZxpTJRgOoW6HKM+YvNa4hm+eAcNmunDiia4ftsXXV03WW+U3zHyOQfnG3zRGqKnAkfkwShGbtoa0hIhY9iouXjM9VCHFhtpWQRrxRVGBekijkz6qkBjItuiIYJUa9VA4woW8Jf+dIJ+asawd9lEgrb+sBjVuZDnl6vF8n+ZGMbr1oZUNq