apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: FwoGZXIvYXdzENv//////////wEaDFFWva2jD3uqPOID2iLVAUOg42cB3v2V6BG+mxh8Muj8yNuAZLy9qFG0Sk32jJBjeF7gYWZEPBeUSoHtXYZF2RPAbasZdxVSXi5fBfpdF4/2O0qlc4S37dgxgS4C7Zd8XQxrjO5R/nM4GOz32Z1/MboS+jS3BPgoiUZWpJZIbTD5myzyWWy7gUf6bozNKs8Vatt0tUpfNLbcN8jSHmV5gGoY6TntpEhoVp6dqKUV/dlpvF2rLBshumxPEL64dqwaDW+JicDvCgHX31TEyk6Qdq8yXASKdVMvnBcaVMulHzQcMqSG8SixzqmkBjItoEj9h3GFDfprasCUau8oNYsN7CPbP+uljMsCWBWzPDL4X5g8i0l6995jxfoD